remote_theme: just-the-docs/just-the-docs

title: Computation & Data Science Education (CDSE) initiative
description: The Computation & Data Science Education (CDSE) initiative helps instructors within the University of Toronto’s Faculty of Arts & Science integrate computational and data-science methods tailored to their disciplines and courses.

favicon_ico: "/assets/images/favicon.ico"

aux_links:
  "Home": "/"
  "Resources": "/resources.html"
