remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
title: Computation and Data Science Education (CDSE) initiative
description: The Computation and Data Science Education (CDSE) initiative helps instructors within the University of Toronto’s Faculty of Arts & Science integrate computational and data-science methods tailored to their disciplines and courses.   
